### ISSUE TITLE
thread 'main' panicked at 'not(empty) : empty may mean false so this need to be true, may not mean', /Users/user/first-order-logic/src/logic/expr.rs:207:28

### ISSUE THREAD

**Issue by Ubsefor** [Nikita-str/first-order-logic#10]

**Comment by Ubsefor** [comment]
<details>
<summary>Log + cargo version </summary>

```bash
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/first-order-logic`
CMD [for help: `help`]:  help
[h | help]: print this msg
[e | exit]: exit from the program
[mcu]: most common unifier for two predicate
       | currently it not print each action,
       | just final result
[std]: step-by-step algorithm for getting empty clause
       | currently end step (resolution) work with max-iter
[max-res-try][x:int]: set amount of tries in resolution method to x

CMD :  h
[h | help]: print this msg
[e | exit]: exit from the program
[mcu]: most common unifier for two predicate
       | currently it not print each action,
       | just final result
[std]: step-by-step algorithm for getting empty clause
       | currently end step (resolution) work with max-iter
[max-res-try][x:int]: set amount of tries in resolution method to x

CMD :  mcu
write left predicate:    
write right predicate:   invalid input UnexpectedToken

CMD :  std
helpful symbs: ∃∃∃ ∀∀∀ ¬¬¬ →→→ ∧∧∧ ∨∨∨
please write a first-order-logic expr:


expr:  #
here no free vars, it fine!
now add logical-not before formula: 
expr:  ¬#
now transform [A → B] into [¬A ∨ B] : 
expr:  ¬#
move in logical-not: 
thread 'main' panicked at 'not(empty) : empty may mean false so this need to be true, may not mean', /Users/rave/Downloads/first-order-logic/src/logic/expr.rs:207:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
> cargo -V
cargo 1.56.0
```
</details>
